name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "54fe422bf66540a1b37fd4eda0e5df67" },
  { binding = "SHARE", id = "5c8264347611408281014af30c4ec471" }
]